#!/bin/sh
# Configuration for login shells 

# Setup Amazon EC2 Command-Line Tools

if [ -x /usr/libexec/java_home ]; then
  export JAVA_HOME=`/usr/libexec/java_home`
fi

export EC2_HOME=/usr/local/opt/ec2-api-tools/
export AWS_ELB_HOME=/usr/local/opt/elb-api-tools/
export EC2_KEY_PATH="${HOME}/.ssh/keys/ec2.x509/"
export EC2_PRIVATE_KEY=`ls ${EC2_KEY_PATH}/pk-*.pem 2>/dev/null`
export EC2_CERT=`ls ${EC2_KEY_PATH}/cert-*.pem 2>/dev/null`
export EC2_URL=https://us-east-1.ec2.amazonaws.com
export AWS_DEFAULT_REGION=us-east-1

export PATH=$PATH:$EC2_HOME/bin:$AWS_ELB_HOME/bin

# Reference to the full (and truly mind-boggling) path for Google AppEngine on Mac OS X
export APPENGINE=/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine

# MySQL and Git execs in $PATH
export PATH=/usr/local/git/bin:/usr/local/mysql/bin:$PATH

# Allow user-specific search path
export PATH=/usr/local/bin:${HOME}/.dotfiles/bin:$PATH


# Startup script for Python
export PYTHONSTARTUP=${HOME}/.pythonrc.py

# git autocomplete
[ -f /usr/local/git/contrib/completion/git-completion.bash ] && . /usr/local/git/contrib/completion/git-completion.bash

# git prompt methods
export GIT_PS1_SHOWUPSTREAM=auto
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
[ -f /usr/local/git/contrib/completion/git-prompt.sh ] && . /usr/local/git/contrib/completion/git-prompt.sh

type __git_ps1 > /dev/null && export GIT_PROMPT='$(__git_ps1 " (%s)")'

# Other completeion available on the host...
[ -f /etc/bash_completion ] && . /etc/bash_completion

# Import interactive shell configuration
[ -f ~/.bashrc ] && source ~/.bashrc
[ -f ~/.bash_aliases ] && source ~/.bash_aliases

export PAGER=less
export LESS='-iMSx4 -FXR'

