#!/bin/sh
# Configuration for login shells

# Setup Amazon EC2 Command-Line Tools

if [ -x /usr/libexec/java_home ]; then
  export JAVA_HOME=`/usr/libexec/java_home`
fi

export EC2_KEY_PATH="${HOME}/.ssh/keys/ec2.x509/"
export EC2_PRIVATE_KEY=`ls ${EC2_KEY_PATH}/pk-*.pem 2>/dev/null`
export EC2_CERT=`ls ${EC2_KEY_PATH}/cert-*.pem 2>/dev/null`
export EC2_URL=https://us-west-2.ec2.amazonaws.com
export AWS_DEFAULT_REGION=us-west-2


# Reference to the full (and truly mind-boggling) path for Google AppEngine on Mac OS X
export APPENGINE=/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine

# MySQL and Git execs in $PATH
export PATH=/usr/local/git/bin:/usr/local/mysql/bin:$PATH

# Allow user-specific search path
export PATH=/usr/local/bin:${HOME}/.dotfiles/bin:$PATH

# Startup script for Python
export PYTHONSTARTUP=${HOME}/.pythonrc.py
export PYTHON_USERCUSTOM=`python -c "import site; print site.getusersitepackages()"`

# Add Postgres path
export PATH="`find /Applications/Postgres.app/ -type d -name bin`:${PATH}"

# Automatically find the Sublime Text path...
export PATH="${PATH}:`find /Applications/Sublime\ Text.app/ -type d -name bin`"

# And finally...
export PATH="$HOME/.dotfiles/bin:${PATH}"

# Import interactive shell configuration
case $- in
  *i*) [ -f ~/.bashrc ] && source ~/.bashrc;;
esac



