#!/bin/sh
# Configuration for login shells 

# Setup Amazon EC2 Command-Line Tools
export JAVA_HOME=`/usr/libexec/java_home`
export EC2_HOME=/usr/local/opt/ec2-api-tools/
export AWS_ELB_HOME=/usr/local/opt/elb-api-tools/
export EC2_KEY_PATH="${HOME}/.ssh/keys/ec2.x509/"
export EC2_PRIVATE_KEY=`ls ${EC2_KEY_PATH}/pk-*.pem 2>/dev/null`
export EC2_CERT=`ls ${EC2_KEY_PATH}/cert-*.pem 2>/dev/null`
export EC2_URL=https://us-east-1.ec2.amazonaws.com
export PATH=$PATH:$EC2_HOME/bin:$AWS_ELB_HOME/bin

# Reference to the full (and truly mind-boggling) path for Google AppEngine on Mac OS X
export APPENGINE=/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine

# MySQL and Git execs in $PATH
export PATH=/usr/local/git/bin:/usr/local/mysql/bin:$PATH

# Startup script for Python
export PYTHONSTARTUP=${HOME}/.pythonrc.py

# git autocomplete
. /usr/local/git/contrib/completion/git-completion.bash


# Import interactive shell configuration
[ -f ~/.bashrc ] && source ~/.bashrc
[ -f ~/.bash_aliases ] && source ~/.bash_aliases




