" VIM runtime config
scriptencoding utf-8

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" My extensions
set runtimepath=~/.vim/rc.d,$VIMRUNTIME
for additive in split(globpath(&runtimepath, 'sb.*.vim'), "\n")
	exe "source ".additive
endfor

" modeline for .vimrc
" vim: foldmethod=marker foldcolumn=3 foldenable tw=120 shiftwidth=4 softtabstop=4 expandtab
