" VIM runtime config
scriptencoding utf-8

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Pull in my minimal configuration...
source ~/.vim/vimrc-minimal

function! GetDotfiles(pattern)
    let command = 'dotfiles -q "' . a:pattern .  '" -w'
    let output = system(command)
    if !v:shell_error
        return 0
    endif
    return split(output, '\n')
endfunction


function! LoadScripts(p, s)
    for @i in a:s
        exe 'source ' . p . @i
    endfor
endfunction

function! LoadColors(p, s)
    for @i in a:s
        exe 'colorscheme ' . p . @i
    endfor
endfunction


" all non-color schemes
call LoadScripts($DOTFILES, GetDotfiles('(.*)(?<!colors)/([^/]*)\.vim'))
call LoadColors($DOTFILES, GetDotfiles('(.*)(colors)/([^/]*)\.vim'))

" modeline for .vimrc
" vim: ft=vim foldmethod=indent foldcolumn=3 foldenable 
" vim: tw=120 shiftwidth=4 softtabstop=4 expandtab
