#!/bin/bash

# COLORIZING {{{
if [ "$TERM" != "dumb" ] && [ -x /usr/bin/dircolors ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    alias dir='ls --color=auto --format=vertical'
    alias vdir='ls --color=auto --format=long'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
# }}}
# FILE LISTING {{{
alias ll='ls -lh'
alias la='ls -A'
alias l='ls -CF'


# }}}

# PROCESS LISTING AND TASK MANAGEMENT {{{
# set my preferred PS output format - this is handled by 'ps' directly
export PS_FORMAT="pid,ppid,state,%cpu,%mem,euser:15,command"
p () {
	case $1 in
		waiting) ps -ae | awk '$2 ~ /^D$/ { print }';;
		watch) shift; PS_FORMAT='pid,user,state,vsz,rsz,%mem,%cpu,command' watch -n 1 ps $@;;
		*) ps;;
	esac
}


# prefer htop over top if htop is present
which htop >/dev/null && alias top='htop'

# }}}

# User/Session Management {{{ 

alias j='jobs -l'
alias d='dirs -l -v'

# a wrapper to print the session status, rather than dumping it with every prompt.
s () {
	local OPTIND=1 system=no
	while getopts :s Opt; do
		case $Opt in
			s) local system=yes;;
		esac
	done

	date

	if [ $system = 'yes' ]; then
		printf "uptime: %s\n" "$(uptime)" 
		if which cpufreq-info >/dev/null; then
			printf "cpufreq: %s\n" "$(cpufreq-info -fm)"
		fi

		printf "me:\t%s\n" "$(who -m)"
		echo 'who:'
		who -T | sed 's/^/\t/'
	fi
		
	echo 'jobs:'
	jobs -l | sed 's/^/\t/'
	
	echo 'dirs:'
	dirs -l -v | sed 's/^/\t/'

	# TODO: other stats... current directory's git status, etc.
	
	

}


# }}}

# some encryption stuff
aes () {
	local OPTIND=1 decrypt=no
	while getopts :u Opt; do
		case $Opt in
			u) decrypt=yes;;
		esac
	done

	case $decrypt in
		yes) aespipe -H rmd160 -e aes256;;
		no) aespipe -d -H rmd160 -e aes256;;
	esac
}


# for my laptop
enable_ibm_hotkey () {
	echo 'echo enable,0x00ffffff > /proc/acpi/ibm/hotkey' | sudo /bin/sh
}


function vimless () {
	$VIMRUNTIME $@
}


# VIM-ness - some friendly shortcuts
alias :q='exit'		
alias :s='history -a'	# save the shell history
alias :m='pushd'	# store a path
alias :d='popd'		# pop a path
alias :marks='dirs -v'	# show all paths


# vim: foldenable foldmethod=marker
